name: "Flarum L10N"
author: "Kitsune Solar <kitsune.solar@gmail.com>"
description: ""
branding:
  icon: ""
  color: ""
inputs:
  repo:
    description: "Repository"
    required: true
  user:
    description: "User"
    required: true
  email:
    description: "E-mail"
    required: true
  token:
    description: "Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.user }}
    - ${{ inputs.email }}
    - ${{ inputs.token }}
